@baseUrl = http://localhost:6400

### Auth Service Health
GET {{baseUrl}}/api/v1/auth/health

### Cookbook Service Health
GET {{baseUrl}}/api/v1/cookbook/health


### Create Cookbook for current user
POST {{baseUrl}}/api/v1/cookbook/create/3
Content-Type: application/json

{
    "title": "Asian"
}

### Add recipe to Cookbook
POST {{baseUrl}}/api/v1/cookbook/add_recipe
Content-Type: application/json

{
    "recipe_id": 3,
    "cookbook_id": 3
}

### Get all recipes based on Cookbook id
GET {{baseUrl}}/api/v1/cookbook/get_recipes/3

### Get all cookbooks based on user id
GET {{baseUrl}}/api/v1/cookbook/get_cookbooks/3

### Recipe Service Health
GET {{baseUrl}}/api/v1/recipe/health

### Create Recipe
POST {{baseUrl}}/api/v1/recipe/create/1
Content-Type: application/json

{
    "title": "Fried Rice",
    "description": "Add left-over rice to pan. Fry under medium heat. Add seasoning and eggs.",
    "category": "Breakfast",
    "image": "Image URL",
    "visibility": "PUBLIC"
}


### Search Service Health
GET {{baseUrl}}/api/v1/search/health

### Users Service Health
GET {{baseUrl}}/api/v1/users/health


### search Service Health
GET {{baseUrl}}/api/v1/search/health

### search Service test
GET {{baseUrl}}/api/v1/search/searchcategory/break

### search Service test
GET {{baseUrl}}/api/v1/search/searchdescription/cereal milk
### Create User
POST {{baseUrl}}/api/v1/users/create_user
Content-Type: application/json

{
    "name": "Sam"
}


### Get all users
GET {{baseUrl}}/api/v1/users/get_all

### Get user by id
GET {{baseUrl}}/api/v1/users/get_user/3
