@baseUrl = http://localhost:6400

### Auth Service Health
GET {{baseUrl}}/api/v1/auth/health

### Cookbook Service Health
GET {{baseUrl}}/api/v1/cookbook/health


### Recipe Service Health
GET {{baseUrl}}/api/v1/recipe/health

### Create Recipe
POST {{baseUrl}}/api/v1/recipe/create/1
Content-Type: application/json

{
    "title": "Cereal",
    "description": "Add cereal to bowl. Add milk to bowl. Mix.",
    "category": "Breakfast",
    "image": "Image URL",
    "visibility": "PUBLIC"
}


### Create User
POST {{baseUrl}}/api/v1/users/create_user
Content-Type: application/json

{
    "name": "John"
}

### Search Service Health
GET {{baseUrl}}/api/v1/search/health

### Users Service Health
GET {{baseUrl}}/api/v1/users/health


### search Service Health
GET {{baseUrl}}/api/v1/search/health

### search Service test
GET {{baseUrl}}/api/v1/search/searchcategory/break

### search Service test
GET {{baseUrl}}/api/v1/search/searchdescription/cereal milk