@baseUrl = http://localhost:6400

### Auth Service Health
GET {{baseUrl}}/api/v1/auth/health

### Cookbook Service Health
GET {{baseUrl}}/api/v1/cookbook/health


### Recipe Service Health
GET {{baseUrl}}/api/v1/recipe/health


### Search Service Health
GET {{baseUrl}}/api/v1/search/health

### Users Service Health
GET {{baseUrl}}/api/v1/users/health
